### ISSUE TITLE
创建项目后执行run.py 报错：提示无allure

### ISSUE THREAD

**Issue by Chen-Ed** [ae86sen/aomaker#1]
pip install aomaker后
aomaker create main
直接执行run.py
因无testcase所以直接结束，但是报错无allure
('allure' 不是内部或外部命令，也不是可运行的程序
或批处理文件。)，
piplist里面是有allure的
是项目有问题？还是说我应该怎么做？
![image](https://github.com/ae86sen/aomaker/assets/53363383/edf002e7-929d-4588-8703-4bdf1908a6fa)

**Comment by ae86sen** [comment]
allure是由两部分组成：
1.allure-pytest，也就是你pip list里看到的
2.allure-command客户端，这不是python包，需要单独安装（依赖java环境）

**Comment by Chen-Ed** [comment]
好的,谢谢~我想起来了,我去下个包配下环境变量吧~~
