### ISSUE TITLE
api封装问题

### ISSUE THREAD

**Issue by lxh1121** [ae86sen/aomaker#13]
hi，有几个比较疑惑，请教一下
1.  接口定义时，request data是已经写好固定格式的，如文档中；
但对于status这种list，编写testcase时有不同的request data.
针对这种情况，我想到的是
 一种是改造当前api参数适配所有testcase
另一种是按照数据分割yaml写测试数据包含接口url、data、断言啊之类，但这时就没必要单独去写一个api函数

想了解下在这个框架下是怎么处理的
```

class Instance(BaseApi):
	def get_instances(self， testdata, testdata1=None?):
        http_data = {
            "owner": self.owner,
            "action": "DescribeInstances",
            "reverse": 1,
            "其他参数": testdata / testdata1
            "status": ["pending", "running", "stopped", testdata],
        }
        resp = self.send_http(http_data)
        return resp
```

**Comment by ae86sen** [comment]
没太看明白，是指接口定义中，有些参数需要通过用例层传入吗？

**Comment by lxh1121** [comment]
> 没太看明白，是指接口定义中，有些参数需要通过用例层传入吗？

对一种这种情况
另一种是比如针对查询资产接口
`
#A用例
data = {name: xx, asserts:[{type:rmb, info:xxx}]}

#B用例
data = {name: xx, asserts:[{type:rmb, info:xxx}, {type:usd, info:ccc}]}
`

**Comment by ae86sen** [comment]
接口定义中，公共参数先抽取出来，其它可以变动的部分，可以设置参数进行控制，这个参数可以在用例层根据用例数据传入，不同用例数据构造不同接口参数定义

**Comment by lxh1121** [comment]
> 接口定义中，公共参数先抽取出来，其它可以变动的部分，可以设置参数进行控制，这个参数可以在用例层根据用例数据传入，不同用例数据构造不同接口参数定义

那就还是这种写法，参考下面的
但这种情况，yaml文件中hpc_submit_job下有几条用例，每条用例参数不一致，我在yaml中用不到的参数也要写防止报错
然后在用例层还有组装

按这种方式，我现在的写法感觉比较繁琐，想知道有没有好办法


```
#Api.py
def get_instances(self， testdata, testdata1=None，num):
        http_data = {
            "owner": self.owner,
            "action": "DescribeInstances",
            "reverse": num，
            "asserts":  testdata1，
            "status": ["pending", "running", "stopped", testdata],
        }
```

```
#test_api.py
@pytest.mark.parametrize("test_data", data_maker("data/api_data/job.yaml", "job", "hpc_submit_job"))
def test_hpc_submit_job(self, test_data):
        resp = job.submit_hpc_job(test_data[a], test_data[b], test_data[c])
        ret_code = resp.get("ret_code")
        # 基类提供的断言方法
        self.assert_eq(ret_code, 0)
```
