### ISSUE TITLE
当接口依赖自身类下时的方法时，dependence的传入问题

### ISSUE THREAD

**Issue by Dduoxi** [ae86sen/aomaker#19]
Q: 当接口依赖自身类下的方法，按照文档通过装饰器传入{class}.{method}
<img width="955" alt="image" src="https://github.com/user-attachments/assets/47b70105-678f-438b-8924-d87082537237">
此方式存在报错
![image](https://github.com/user-attachments/assets/f9000e0a-44cb-4656-8e44-29f250c54023)
看源码取类时仅通过【.】分割传入的str，类并没有被实例化
![image](https://github.com/user-attachments/assets/1d3f9840-941b-47f0-8d6a-7cdbc4a6acf2)
后续直接执行方法就会有上述报错

因此
![image](https://github.com/user-attachments/assets/2c0e01f3-c7fa-479c-b8fd-307a1a9c0a91)
此处是否应该先实例化后再调依赖接口

**Comment by ae86sen** [comment]
是的，文档里写错了，需要用实例对象调用

**Comment by Dduoxi** [comment]
也可以不写错，真的要去传入自身实例还要再包一层会不会太重了，直接在_call_dependence里手动实例一次就行会不会好点

**Comment by Dduoxi** [comment]
已解决，解决为每个ao后接实例对象，传入为实例对象
