### ISSUE TITLE
pycharm执行run.py时，会在执行case前后出现gbk编码错误的错误提示，命令行启动则不会

### ISSUE THREAD

**Issue by Chen-Ed** [ae86sen/aomaker#2]
![image](https://github.com/ae86sen/aomaker/assets/53363383/89a61816-77d9-4c2a-b05d-41970badd287)
![image](https://github.com/ae86sen/aomaker/assets/53363383/fded84ce-eb91-45ef-b8b0-df538272b36d)

**Comment by ae86sen** [comment]
看下pycharm的console encoding是否设置为utf-8

**Comment by Chen-Ed** [comment]
> 看下pycharm的console encoding是否设置为utf-8

是的呀 是utf-8
![1697513233272](https://github.com/ae86sen/aomaker/assets/53363383/ca505b7d-3480-4593-9f2c-24bc610565f3)

**Comment by Chen-Ed** [comment]
在作者的帮助下解决了这毛病！是pycharm引起的，把这两处pycharm设置为utf8就好了
![cb11a6104432c1fbe88db73cd49338d](https://github.com/ae86sen/aomaker/assets/53363383/c327546a-79dc-44a6-a053-6b1e5c565de2)
![4c6253fc6db2151cf88ee163c97e949](https://github.com/ae86sen/aomaker/assets/53363383/ab36adf8-2734-4f9c-a543-93896a1b9188)
![c1cf9a95bb81ac088cd4e27e8f2db05](https://github.com/ae86sen/aomaker/assets/53363383/23bb8e0a-5913-4832-b6ba-eb40ac7836ac)

**Comment by balanceliu** [comment]
# 设置标准输出的编码为 utf-8
sys.stdout.reconfigure(encoding='utf-8')
作者可以加上这一行代码。
