### ISSUE TITLE
dependence依赖的接口，是同一个类的方法执行报错

### ISSUE THREAD

**Issue by Test-jimmy** [ae86sen/aomaker#5]
![image](https://github.com/ae86sen/aomaker/assets/70614526/c19b5bfc-967c-456f-bf9d-d32422c807a9)
修改_aomaker.py220行能正常执行
 res = eval(f'{class_}.{method_}(*{out_args},**{out_kwargs})')   >> res = eval(f'{class_}().{method_}(*{out_args},**{out_kwargs})')  
![image](https://github.com/ae86sen/aomaker/assets/70614526/54692fdc-3e6c-4ccd-9a56-391d13e8c96c)

**Comment by ae86sen** [comment]
有个默认条件，可能文档没写清楚。即，每个api模块下的最后，需要完成这个接口类的实例化，如在system.py模块下，接口类System定义完后，声明system = System()。（目的：单例）

**Comment by ae86sen** [comment]
like this：
*apis/system.py*
```python
class System(Baseapi):
  def xxx():
    ...

system = System()
```

**Comment by Test-jimmy** [comment]
已解决
